### ISSUE TITLE
Missing parameter in listener.update_device() call causes Home Assistant integration failures

### ISSUE THREAD

**Issue by appositeit** [tuya/tuya-device-sharing-sdk#28]
# Bug Report: Missing parameter in listener.update_device() call causes Home Assistant integration failures

## Bug Description

The `tuya_sharing` library version 0.2.1 has a critical bug in `manager.py` where `listener.update_device()` is called with insufficient parameters, causing widespread Home Assistant integration failures.

## Environment

- **Package**: `tuya-device-sharing-sdk` version 0.2.1
- **Affected File**: `tuya_sharing/manager.py` (line ~142)
- **Impact**: All Home Assistant users with Tuya integration
- **Severity**: Critical (causes thousands of daily errors)

### Current Buggy Code
```python
def __update_device(self, device: CustomerDevice):
    for listener in self.device_listeners:
        listener.update_device(device)  # ❌ Missing required parameter
```

### Expected Interface (Home Assistant)
Home Assistant's device listeners expect this signature:
```python
def update_device(self, device: CustomerDevice, updated_status_properties: list[str] | None = None):
```

### Error Symptoms
- Thousands of daily errors in Home Assistant logs
- Tuya devices become non-functional
- Integration setup failures
- Poor system performance

## Reproduction Steps

1. Install Home Assistant with Tuya integration
2. Add Tuya devices via Smart Life app integration
3. Observe massive error spam in logs:
   ```
   TypeError: SharingDeviceListener.update_device() missing 1 required positional argument: 'updated_status_properties'
   ```

## Solution

Update the method signature and calls to include the missing parameter:

```python
def __update_device(self, device: CustomerDevice, updated_status_properties: list[str] | None = None):
    for listener in self.device_listeners:
        listener.update_device(device, updated_status_properties)  # ✅ Correct signature
```

### Before Fix
- 4,000+ daily errors per Home Assistant instance
- Non-functional Tuya devices
- Polluted log files
- Degraded system performance

### After Fix (Verified)
- Zero Tuya integration errors
- All devices working properly  
- Clean logs
- Optimal performance

## Testing

This fix has been successfully tested in production:
- ✅ Home Assistant 2025.5.x
- ✅ Docker container environment
- ✅ 100+ Tuya entities functioning correctly
- ✅ 99% error reduction achieved

## Related Issues

This bug affects numerous Home Assistant users, as evidenced by recent issues in the home-assistant/core repository:
- #134695: "After Update to 2025.1 official Tuya dont work"
- #144785: "Error Network Tuya after update / RESTART"  
- #144791: "Setup error"
- #144796: "tuya network error"

## Proposed Fix

I can submit a pull request with the fix if maintainers confirm this approach. The change is minimal and backward-compatible.

---

**Priority**: High - This affects thousands of Home Assistant users globally
**Complexity**: Low - Simple parameter addition  
**Risk**: Minimal - Backward compatible change

**Comment by FredrikM97** [comment]
Think this is solved in the dev branch?

**Comment by appositeit** [comment]
Great to hear! Thanks!
